language: python
python:
  - "2.7"
  - "3.4"
addons:
  apt:
    packages:
    - libssl-dev
    - libsasl2-dev
    - sasl2-bin
    - swig
    - python-dev
    - python3-dev
    - uuid-dev
install:
  - pip install -r test-requirements.txt
  - pip install .
# command to run tests
script: tests/test-runner
